## Unit 5 Numpy_Broadcast Quiz
* The objective of this quiz is to understand how to use how broadcasting works with Numpy arrays.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")
import pickle
import comp116

Numpy version is 1.24.3


## Broadcasting is a feature of Numpy arrays that allows arithmetic operations between arrays that are not necessarily of compatible dimension for the computation.
* During such an operation, the arrays are "broadcast" to a certain size that makes the operartion possible.
* Knowledge of broadcasting is useful in a number of places, for example deep learning methids.

## Create  a Numpy array `A` as a (3, 3) array of random integers.

In [2]:
# Your code here
my_rng = np.random.default_rng()

A = my_rng.integers(0,1000,(3,3))
print(A)

[[862  63 914]
 [649 261 718]
 [201 170 972]]


## Create a second numpy array, `b` of size (3,) of random integers.

In [3]:
# Your code here
b = my_rng.integers(0,1000,(3,))
print(b)

[199 161 652]


## Perform the operation `A*b`

In [4]:
# Your code below
Ab = A*b
print(Ab)

[[171538  10143 595928]
 [129151  42021 468136]
 [ 39999  27370 633744]]


## Explain why it was possible to compute `A*b` in the above case. 
* As part of your explanation, show the broadcast versions of `A` and `b`

### Explanation here.
It is easy to multiply them because A.y and b.x have the same number or measurements and b.y is 1 so it can be repeated to fit A.x.

## Now create a third array `c` that is a (2,) array of random integers.

In [5]:
# Your code here
c = my_rng.integers(0,1000,(2,))
print(c)

[813 689]


## Perform the operation `A*c`

In [6]:
# Your code here
Ac = A*c
print(Ac)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

## Explain, in terms of broadcasting, why it was not possible to compute `A*c`

### Your explanation here.
Although c.y is 1 making A.x irrelevant, c.x = 2 and A.y = 3 are different and neither is 1 making multiplication between the two arrays impossible. There is no way to choose which numbers in each array multiply each number in the other array nor is it possible to determine the shape of the output array.