## Unit 5 Numpy_Random_Matrix Quiz
* The objective of this quiz is to use Numpy for generating random values and look at simple array manipulation.

In [1]:
## Import Numpy and check version
import numpy as np
print(f"Numpy version is {np.__version__}")

Numpy version is 1.24.3


### Random numbers are frequently used in Data Science.
* Generating random numbers (or rather pseudo-random numbers) is an important function.
* Numpy provides a random number module called `numpy.random`.
* You can learn more about generating random numbers [here](https://numpy.org/doc/stable/reference/random/index.html) and [here](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random).

### Create a random number generator called `my_rng` using the `default_rng()` method in `np.random`. Use the default seed.

In [2]:
# Write your code below.
my_rng = np.random.default_rng()

### Now use `my_rng` to generate a 3X3 numpy array of random values.
* Print out this array

In [3]:
# Write your code below.
randomArray = my_rng.random((3, 3))
#array = np.array(my_rng)
print(randomArray)

[[0.12153234 0.34850728 0.40522124]
 [0.85372888 0.83941921 0.41319377]
 [0.95258223 0.56607472 0.41642878]]


### What is the distribution of the random numbers generated and what is the range?
* This is not something to be computed, simply look up this information in the [`np.random` web page](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html).

#### Answer below.
Uniform distribution from 0 to 1, not including 1.

### Use the Numpy array created above to create a second Numpy array of random numbers that is between -10.0 and 10.0.
* This question requires you to figure out the mapping that will convert a set of random numbers that are distributed as found in the previous question to have the range from -10.0 to 10.0.
* The form of the distributon does not change.

In [4]:
# Show your code below.
randomArray2 = my_rng.uniform(-10, 10, (3, 3))
print(randomArray2)

[[-0.63400526 -7.69523221 -3.43158598]
 [-1.27280838 -3.93746012  5.11457234]
 [ 4.91233085  3.28349324 -3.55221197]]


### `np.random` can also generate random integers. Generate a 3X3 array of random integers between 0 and 10.

In [5]:
# Your code here.
randomArray3 = my_rng.integers(0,10,(3,3))
print(randomArray3)

[[1 2 1]
 [6 9 9]
 [9 4 9]]


### `np.random` can also generate various common distributions. Generate a 3X3 array of numbers from a normal distribution with mean 10 and standard deviation 2.

In [6]:
# Your code here
randomArray4 = my_rng.normal(10,2,(3,3))
print(randomArray4)

[[12.15834982  9.92082819  6.9701669 ]
 [ 9.84395549 12.72468771 12.80647828]
 [ 9.10721126  8.32510045  9.94014137]]


### Call the 3X3 matrix of normal random variables generated in the last step `gm3`.
* Use Numpy methods to create two other numpy arrays, `row_sum` and `col_sum`:
* `row_sum` should be the length 3 array of the sum of the rows of `gm3`.
* `col_sum` should be the length 3 array of the sum of the columns of `gm3`

In [7]:
# Your code here
row_sum = np.sum(randomArray4, axis=1)
col_sum = np.sum(randomArray4, axis=0)
print(f'The row sums are {row_sum} and the column sums are {col_sum}.')

The row sums are [29.04934491 35.37512148 27.37245308] and the column sums are [31.10951657 30.97061635 29.71678656].
